// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChP5ecejWg0XFz5_U0IZZnBTDhCjP4INU',
    appId: '1:140655666310:web:7e376122b718903ddb9d07',
    messagingSenderId: '140655666310',
    projectId: 'fyp-plantify',
    authDomain: 'fyp-plantify.firebaseapp.com',
    storageBucket: 'fyp-plantify.appspot.com',
    measurementId: 'G-0XK3JTWM55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEF0-HN1hWLs8h8dvQPAYnRARIOtlSR6w',
    appId: '1:140655666310:android:4bfa03416adc599adb9d07',
    messagingSenderId: '140655666310',
    projectId: 'fyp-plantify',
    storageBucket: 'fyp-plantify.appspot.com',
  );
}
